[alias]
xtask = "run --package xtask --"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-musl.env]
CC_aarch64_unknown_linux_musl = "aarch64-linux-gnu-gcc"
CFLAGS_aarch64_unknown_linux_musl = "-D_FORTIFY_SOURCE=0 -static"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.armv7-unknown-linux-musleabihf.env]
CC_armv7_unknown_linux_musleabihf = "arm-linux-gnueabihf-gcc"
CFLAGS_armv7_unknown_linux_musleabihf = "-D_FORTIFY_SOURCE=0 -static"

[target.x86_64-unknown-linux-gnu]
linker = "gcc"