name = "Security"

[[data]]
name = "UFW Firewall Baselines (CTT)"
description = "Developed to ease iptables firewall configuration, UFW provides a user friendly way to create an IPv4 or IPv6 host-based firewall. This command installs UFW and configures UFW based on CTT's recommended rules. For more information visit: https://christitus.com/linux-security-mistakes"
script = "ufw-baselines.sh"
task_list = "I SS"

[[data.preconditions]]
matches = false
data = "command_exists"
values = [ "firewall-cmd" ]

[[data]]
name = "FirewallD Firewall Baselines (CTT)"
description = "Configure FirewallD with CTT's recommended baseline rules for improved system security. For more information visit: https://christitus.com/linux-security-mistakes"
script = "firewalld-baselines.sh"
task_list = "I SS"

[[data.preconditions]]
matches = true
data = "command_exists"
values = [ "firewall-cmd" ]

[[data]]
name = "iptables Firewall Baselines"
description = "Configure raw iptables with recommended security baseline rules. iptables is the underlying firewall technology in Linux used by both UFW and FirewallD, but can be configured directly for more granular control."
script = "iptables-baselines.sh"
task_list = "I SS"

[[data.preconditions]]
matches = false
data = "command_exists"
values = [ "firewall-cmd", "ufw" ]
